name: AdvaitaHealthAdapter
description: External Adapter for TCMAPI from the AdvaitaHealth
node_identifier: AdvaitaHealthTcmApi
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: TCMAPI
  - url: http://advaita.world
parameters:
  - base
  - quote
